### ISSUE TITLE
"`pyani.scripts` module not found" when installing development branch

### ISSUE THREAD

**Issue by nickp60** [widdowquinn/pyani#119]
#### Summary:
When installed on the development branch, a "module not found" error occurs upon execution of `pyani`.  This only happens when installed with `python setup.py install`, but does not occur when set up with `python setup.py develop`.

#### Description:
 It appears that pyani cannot locate all the subdirectories within the package.

#### Reproducible Steps:
Setting up a temporary environment on linux:
```
git clone pyani
cd pyani
git checkout development
conda create -n tmp biopython mummer
```
#### Current Output:

Running working after setting up in develop mode:
```
$ python setup.py develop
$ pyani -h
# contents of help message
```
Running fails when setting up in "install" mode
```
$ python setup.py install
$ pyani -h
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/users/nickp60/miniconda3/envs/tmp/bin/pyani", line 11, in <module>
    load_entry_point('pyani==0.3.0a0', 'console_scripts', 'pyani')()
  File "/home/users/nickp60/miniconda3/envs/tmp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/users/nickp60/miniconda3/envs/tmp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/home/users/nickp60/miniconda3/envs/tmp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/home/users/nickp60/miniconda3/envs/tmp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'pyani.scripts'
```

#### Expected Output:
Would expect to see the help message, etc

#### Suggested fix
 I believe line 58 in `setup.py` needs to either be:
  `packages=["pyani", "pyani/scripts", "pyani/scripts/subcommands"],`
or
   `packages=setuptools.find_packages(),`

#### pyani Version:
pyani==0.3.0a0

#### Python Version:
Python 3.5.0 :: Continuum Analytics, Inc.

#### Operating System:
In this case, Debian 9.5.  This mainly appears to be an issue installing on Linux.  I have gotten it on OSX as well, but its harder to reproduce.

**Comment by widdowquinn** [comment]
Thanks for the report, Nick.

I chose to use your suggestion of using `setuptools.find_packages()` to automatically locate the subpackages, and this should be live in commit 55ec088 now.
