### ISSUE TITLE
pyani listdeps exception if missing command line blastall

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#218]
Using current master branch on Linux:

```
$ pyani listdeps
System information
	Platorm==Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
	Python==3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0]
Installed pyani Python dependendencies...
	Pillow==Not Installed (-)
	biopython==1.77.dev0 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	matplotlib==3.1.3 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	namedlist==1.7 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	networkx==2.3 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	numpy==1.17.4 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	openpyxl==Not Installed (-)
	pandas==1.1.0 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	scipy==1.4.1 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	seaborn==0.10.1 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	sqlalchemy==1.3.6 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	tqdm==4.41.1 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
Installed pyani development dependendencies...
	bandit==1.6.2 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	black==19.3b0 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==3.7.9 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	jinja2==2.10.1 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	mypy==Not Installed (-)
	pydocstyle==5.0.2 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
	pylint==Not Installed (-)
	pytest==Not Installed (-)
	pytest-cov==Not Installed (-)
	sphinx==2.3.1 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
Installed pyani pip-install dependendencies...
	pre-commit==Not Installed (-)
	pytest-ordering==Not Installed (-)
	sphinx-rtd-theme==0.4.3 (/mnt/du-synology/v1shr1/scratch/pc40583/apps/conda/lib/python3.7/site-packages)
Installed third-party tool versions...
	blast+==Linux_2.9.0+
	nucmer==Linux_3.1
Traceback (most recent call last):
  File "/mnt/xxx/conda/bin/pyani", line 8, in <module>
    sys.exit(run_main())
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/scripts/pyani_script.py", line 105, in run_main
    returnval = args.func(args)
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/scripts/subcommands/subcmd_listdeps.py", line 86, in subcmd_listdeps
    for tool, version in get_tool_versions():
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/dependencies.py", line 117, in get_tool_versions
    yield (name, func())
  File "/mnt/xxx/conda/lib/python3.7/site-packages/pyani/aniblastall.py", line 69, in get_version
    check=False,  # blastall doesn't return 0
  File "/mnt/xxx/conda/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/mnt/xxx/conda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/xxx/conda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('blastall'): PosixPath('blastall')
```

Looks like an easy fix, catch the exception and report "Not installed"

**Comment by EricDeveaud** [comment]
one solution may be 

`import distutils.spawn`

test if blast_exe is available before trying to get his version
```
# check if blastall is found before trying to call it
if distutils.spawn.find_executable(blast_exe) is None:
      #handle the problem, message, other... 
```

regards

Eric

**Comment by widdowquinn** [comment]
Same issue as #276 and fixed there.
