### ISSUE TITLE
pyani listdeps broken :: pyani/aniblastall.py :: blastall doe not have --version option

### ISSUE THREAD

**Issue by EricDeveaud** [widdowquinn/pyani#232]
#### Summary:
running `pyany listdeps` from fresh cloned repo (commit 0081885c0c5c81e6885a533279c56749c5c12bd4)
I have the following error

```
Installed third-party tool versions...
	blast+==Linux_2.10.0+
	nucmer==Linux_3.1
Traceback (most recent call last):
  File "/opt/gensoft/exe/pyani/0.3.0a0/bin/pyani", line 8, in <module>
    sys.exit(run_main())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/pyani_script.py", line 105, in run_main
    returnval = args.func(args)
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/subcommands/subcmd_listdeps.py", line 86, in subcmd_listdeps
    for tool, version in get_tool_versions():
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/dependencies.py", line 117, in get_tool_versions
    yield (name, func())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/aniblastall.py", line 74, in get_version
    version = re.search(  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'
```

#### pyani Version:
pyani does not provide a way to know his version ;-)
a `--version` flag will be nice.

anyway 
```
average_nucleotide_identity.py --version 
average_nucleotide_identity.py: pyani 0.3.0-alpha
```
code clone from commit 0081885c0c5c81e6885a533279c56749c5c12bd4

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

see above problem ;-)

```
System information
        Platorm==Linux-4.18.0-193.19.1.el8_2.x86_64-x86_64-with-glibc2.2.5
        Python==3.8.1 (default, May 22 2020, 14:09:57)
[GCC 9.2.0]
Installed pyani Python dependendencies...
        Pillow==8.1.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        biopython==1.78 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        matplotlib==3.3.3 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        namedlist==1.8 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        networkx==2.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        numpy==1.19.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        openpyxl==Not Installed (-)
        pandas==1.2.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        scipy==1.6.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        seaborn==0.11.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        sqlalchemy==1.3.22 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
        tqdm==4.56.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
Installed pyani development dependendencies...
        bandit==Not Installed (-)
        black==Not Installed (-)
        coverage==Not Installed (-)
        doc8==Not Installed (-)
        flake8==Not Installed (-)
        jinja2==Not Installed (-)
        mypy==Not Installed (-)
        pydocstyle==Not Installed (-)
        pylint==Not Installed (-)
        pytest==Not Installed (-)
        pytest-cov==Not Installed (-)
        sphinx==Not Installed (-)
Installed pyani pip-install dependendencies...
        pre-commit==Not Installed (-)
        pytest-ordering==Not Installed (-)
        sphinx-rtd-theme==Not Installed (-)
Installed third-party tool versions...
        blast+==Linux_2.10.0+
        nucmer==Linux_3.1
Traceback (most recent call last):
  File "/opt/gensoft/exe/pyani/0.3.0a0/bin/pyani", line 8, in <module>
    sys.exit(run_main())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/pyani_script.py", line 105, in run_main
    returnval = args.func(args)
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/scripts/subcommands/subcmd_listdeps.py", line 86, in subcmd_listdeps
    for tool, version in get_tool_versions():
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/dependencies.py", line 117, in get_tool_versions
    yield (name, func())
  File "/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages/pyani/aniblastall.py", line 74, in get_version
    version = re.search(  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'
```

problem is that `blastall` does not provide a --version  option. when called `blastall --version` it display an error message.
tested with legacy blast 2.2.19, 2.2.21, 2.2.25, 2.2.26.

```
tars-submit0:~ > blastall --version 
[blastall] ERROR: Invalid argument: --version
``` 
it should be called with `--help` instead of `--version`

furthermore blastall output in this case is deirected to `stdout` not `stderr`

changing code from 
```
This is concatenated with the OS name.
    """
    cmdline = [blast_exe, "-version"]
    result = subprocess.run(
        cmdline,  # type: ignore
        shell=False,
        stdout=subprocess.PIPE,  # type: ignore
        stderr=subprocess.PIPE,
        check=False,  # blastall doesn't return 0
    )
    version = re.search(  # type: ignore
        r"(?<=blastall\s)[0-9\.]*", str(result.stderr, "utf-8")
    ).group()
```
to 
```
    This is concatenated with the OS name.
    """
    cmdline = [blast_exe, '--help']
    result = subprocess.run(
        cmdline,  # type: ignore
        shell=False,
        stdout=subprocess.PIPE,  # type: ignore
        stderr=subprocess.PIPE,
        check=False,  # blastall doesn't return 0
    )
    
    version = re.search(  # type: ignore
        r"(?<=blastall\s)[0-9\.]*", str(result.stdout, "utf-8")
```

fix the problem see:

```
pyani listdeps 2>&1| tee log
System information
	Platorm==Linux-4.18.0-193.19.1.el8_2.x86_64-x86_64-with-glibc2.2.5
	Python==3.8.1 (default, May 22 2020, 14:09:57) 
[GCC 9.2.0]
Installed pyani Python dependendencies...
	Pillow==8.1.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	biopython==1.78 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	matplotlib==3.3.3 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	namedlist==1.8 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	networkx==2.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	numpy==1.19.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	openpyxl==Not Installed (-)
	pandas==1.2.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	scipy==1.6.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	seaborn==0.11.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	sqlalchemy==1.3.22 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	tqdm==4.56.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
Installed pyani development dependendencies...
	bandit==Not Installed (-)
	black==Not Installed (-)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==Not Installed (-)
	jinja2==Not Installed (-)
	mypy==Not Installed (-)
	pydocstyle==Not Installed (-)
	pylint==Not Installed (-)
	pytest==Not Installed (-)
	pytest-cov==Not Installed (-)
	sphinx==Not Installed (-)
Installed pyani pip-install dependendencies...
	pre-commit==Not Installed (-)
	pytest-ordering==Not Installed (-)
	sphinx-rtd-theme==Not Installed (-)
Installed third-party tool versions...
	blast+==Linux_2.10.0+
	nucmer==Linux_3.1
	blastall==Linux_2.2.26
[gensoft@345ddfccadad pyani-0.3.0a0]$ 
[gensoft@345ddfccadad pyani-0.3.0a0]$ pyani listdeps 2>&1| tee log
System information
	Platorm==Linux-4.18.0-193.19.1.el8_2.x86_64-x86_64-with-glibc2.2.5
	Python==3.8.1 (default, May 22 2020, 14:09:57) 
[GCC 9.2.0]
Installed pyani Python dependendencies...
	Pillow==8.1.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	biopython==1.78 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	matplotlib==3.3.3 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	namedlist==1.8 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	networkx==2.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	numpy==1.19.5 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	openpyxl==Not Installed (-)
	pandas==1.2.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	scipy==1.6.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	seaborn==0.11.1 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	sqlalchemy==1.3.22 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
	tqdm==4.56.0 (/opt/gensoft/exe/pyani/0.3.0a0/venv/lib/python3.8/site-packages)
Installed pyani development dependendencies...
	bandit==Not Installed (-)
	black==Not Installed (-)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==Not Installed (-)
	jinja2==Not Installed (-)
	mypy==Not Installed (-)
	pydocstyle==Not Installed (-)
	pylint==Not Installed (-)
	pytest==Not Installed (-)
	pytest-cov==Not Installed (-)
	sphinx==Not Installed (-)
Installed pyani pip-install dependendencies...
	pre-commit==Not Installed (-)
	pytest-ordering==Not Installed (-)
	sphinx-rtd-theme==Not Installed (-)
Installed third-party tool versions...
	blast+==Linux_2.10.0+
	nucmer==Linux_3.1
	blastall==Linux_2.2.26
```

hope this will help

regards

Eric

**Comment by baileythegreen** [comment]
> #### pyani Version:
> pyani does not provide a way to know his version ;-)
> a `--version` flag will be nice.

This is fixed in #263. (But also, running just `pyani` outputs it in version `0.3.0a0`, which is the version number shows up in your traceback.

@widdowquinn None of the subcommands seem to have a working `--version` flag, despite collecting version information; I'll see about adding that to #263.

**Comment by baileythegreen** [comment]
@widdowquinn 

This issue appears to be a bit OS-specific.

On MacOS, if I try to get `blastall`'s version, I get:

```
$ blastall --version
[blastall 2.2.26] ERROR: Invalid argument: --version
```
or
```
$ blastall -version
[blastall 2.2.26] ERROR: Number of database sequences to show one-line descriptions for (V) [ersion] is bad or out of range [? to ?]
```
which, when parsed by `ani_blastall.get_version`, works fine, because the version number is still present:

```
$ pyani listdeps
System information
	Platorm==macOS-10.13.6-x86_64-i386-64bit
	Python==3.8.3 (default, May 19 2020, 13:54:14) 
[Clang 10.0.0 ]
Installed pyani Python dependendencies...
	Pillow==8.0.0 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	biopython==1.78 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	matplotlib==3.1.3 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	namedlist==1.8 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	networkx==2.5.1 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	numpy==1.20.2 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	openpyxl==3.0.7 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	pandas==1.0.5 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	scipy==1.5.1 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	seaborn==0.11.1 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	sqlalchemy==1.3.10 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	tqdm==4.60.0 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
Installed pyani development dependendencies...
	bandit==1.7.0 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	black==20.8b1 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	codecov==2.1.11 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	coverage==5.5 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	doc8==0.8.1 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	flake8==3.8.4 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	jinja2==2.11.3 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	mypy==0.812 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	pydocstyle==6.0.0 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	pylint==2.6.0 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	pytest==6.2.3 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	pytest-cov==2.11.1 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	sphinx==3.5.4 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
Installed pyani pip-install dependendencies...
	pre-commit==2.10.0 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	pytest-ordering==0.6 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
	sphinx-rtd-theme==0.5.1 (/Users/baileythegreen/Software/miniconda3/lib/python3.8/site-packages)
Installed third-party tool versions...
	blast+==Darwin_2.6.0+
	nucmer==Darwin_3.1
	blastall==Darwin_2.2.26
```

The issue appears to be that the output for Linux differs: the version number is missing here:

> ```
> tars-submit0:~ > blastall --version 
> [blastall] ERROR: Invalid argument: --version
> ```

**Comment by widdowquinn** [comment]
I can no longer test this on macOS (the `conda` `blast-legacy`) executable does not run on Big Sur.

The `get_version()` call for this does:

```python
cmdline = [blast_exe, "-version"]
```

On Linux this gives (for me):

```bash
$ blastall -version
[blastall] ERROR: Number of database sequences to show one-line descriptions for (V) [ersion] is bad or out of range [? to ?]
```

But just calling the tool gives:

```bash
$ blastall

blastall 2.2.26   arguments:

  -p  Program Name [String]
[...]
```

I suggest we:

1. gracefully catch the failure to get a version with a "Could not determine blastall version" or similar notice.
2. remove the `"-version"` argument from the `cmdline` assignment.

**Comment by baileythegreen** [comment]
Just calling the tool on MacOS (High Sierra) looks the same:

```
$ blastall

blastall 2.2.26   arguments:

  -p  Program Name [String]
[...]
```

Are the two options you're proposing mutually exclusive alternatives? The first one might be good to include more generally (not just for blastall), in case something can't be found.

**Comment by widdowquinn** [comment]
> Are the two options you're proposing mutually exclusive alternatives? The first one might be good to include more generally (not just for blastall), in case something can't be found.

No - I'm implicitly going for "can't find blastall" and the like with (1); (2) is just to account for how we need to call `blastall`.
