### ISSUE TITLE
ImportError: cannot import name '_api' from 'matplotlib'

### ISSUE THREAD

**Issue by spencer411** [widdowquinn/pyani#264]
#### Summary:
I installed pyani using miniconda following the instructions on this github page, but get the error message below when attempting to run the average_nucleotide_identity.py script.

#### Description:
Describe the issue in detail, as clearly as possible.

#### Reproducible Steps:
source /network/rit/lab/andamlab/bin/miniconda3/etc/profile.d/conda.sh
conda activate pyani_env
umask g+rwx
average_nucleotide_identity.py -i maddy_pyani/ -o maddy_pyani/test_ANIm_output -m ANIm -g
exit 0

#### Current Output:
Traceback (most recent call last):
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/pyani/bin/average_nucleotide_identity.py", line 168, in <module>
    from pyani import (
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/pyani/lib/python3.8/site-packages/pyani/pyani_graphics.py", line 55, in <module>
    import matplotlib.pyplot as plt  # noqa: E402
  File "/network/rit/lab/andamlab/bin/miniconda3/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/pyplot.py", line 43, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/network/rit/lab/andamlab/bin/miniconda3/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/figure.py", line 18, in <module>
    from matplotlib import docstring, projections
  File "/network/rit/lab/andamlab/bin/miniconda3/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/pyani/lib/python3.8/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/pyani/lib/python3.8/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 22, in <module>
    from matplotlib import _api, artist, cbook, docstring
ImportError: cannot import name '_api' from 'matplotlib' (/network/rit/lab/andamlab/bin/miniconda3/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/__init__.py)

#### Expected Output:
I actually have run this in the past without any issues, getting the full output folder. Not sure why I started to get this error.

#### pyani Version:
0.2.10

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

#### Python Version:
3.8

#### Operating System:
linux

**Comment by widdowquinn** [comment]
Hi @spencer411 - thanks for using `pyani`.

That looks to be a `matplotlib` issue, with the package calling its own internals. Have you changed versions of this package recently?

Can you please attempt to import `matplotlib` from a Python REPL in the same environment, e.g.

```bash
$ python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> 
```

and let us know what happens.

From the error reported above, I would expect this to fail. If it does fail, then that's a `matplotlib` issue, rather than `pyani`.

L.
