### ISSUE TITLE
math domain error

### ISSUE THREAD

**Issue by MathGon** [widdowquinn/pyani#4]
I manage to perform previous analysis with your *amazing* script. unfortunatly I've a problem with a new attempt

```
python average_nucleotide_identity.py -i /home/mgonnet/Documents/84_3/ -o /home/mgonnet/Documents/84_3/out/ -m ANIm -g --gformat pdf -v
```

raising a `ValueError: math domain error` when trying to call `matplotlib/ticker.py`

```
INFO: Writing heatmap to /home/mgonnet/Documents/84_3/out/ANIm_similarity_errors.pdf
Traceback (most recent call last):
  File "average_nucleotide_identity.py", line 666, in <module>
    draw(results, methods[args.method][1])
  File "average_nucleotide_identity.py", line 561, in draw
    classes=get_labels(args.classes))
  File "/home/mgonnet/Soft/pyani/pyani/pyani_graphics.py", line 209, in heatmap_mpl
    cb = fig.colorbar(ax_map, scale_ax, ticks=cbticks)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1500, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 1316, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 892, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 321, in __init__
    self.draw_all()
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 346, in draw_all
    self._config_axes(X, Y)
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 440, in _config_axes
    self.update_ticks()
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 371, in update_ticks
    ticks, ticklabels, offset_string = self._ticker()
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 591, in _ticker
    formatter.set_locs(b)
  File "/usr/lib/python2.7/dist-packages/matplotlib/ticker.py", line 523, in set_locs
    self._set_format(vmin, vmax)
  File "/usr/lib/python2.7/dist-packages/matplotlib/ticker.py", line 584, in _set_format
    loc_range_oom = int(math.floor(math.log10(loc_range)))
ValueError: math domain error
```

Any idea?

**Comment by MathGon** [comment]
Sorry. I found my error. After reinstallation of mummer, I forgot to export the executable directory to $PATH

**Comment by widdowquinn** [comment]
Thanks, MathGon - I'm glad it was all resolved easily. I'll close this, now.
