### ISSUE TITLE
numpy: No module named 'version'

### ISSUE THREAD

**Issue by ireneortega** [widdowquinn/pyani#423]
#### Summary:
After installing pyani with conda, the python script average_nucleotide_identity.py is not working as No module named 'version' is found.

#### Reproducible Steps:
conda create --name pyani_env python=3.9 pyani

#### Current Output:
(pyani_env) $ average_nucleotide_identity.py -h
Traceback (most recent call last):
  File "/home/iortsan/anaconda3/envs/pyani_env/bin/average_nucleotide_identity.py", line 158, in <module>
    import pandas as pd
  File "/home/iortsan/.local/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: No module named 'version'

#### Expected Output:
Help of average_nucleotide_identity.py 

#### pyani Version:
bioconda/noarch::pyani-0.2.12-pyhdfd78af_0

#### Python Version:
Python 3.9.18

#### Operating System:
"CentOS Linux 7 (Core)

**Comment by kiepczi** [comment]
Hi @ireneortega,

Thank you very much for showing interest in `pyANI`! Unfortunately, I'm unable to reproduce the issue on my end (macOS).

I suspect something went wrong during the installation, and `numpy` might not have been installed properly. Could you please confirm which dependencies are installed in your `pyani_env` environment?

If you haven't done so already, you can type the following after activating the conda environment:

```bash
conda list
```

This command should return a list of all dependencies installed in that environment and hopefully provide me with some clues.

For reference, this is what is returned with `conda list` when following the same installation process as you:

```bash
(base) angelikakiepas@Angelikas-MacBook-Pro ~ % conda activate pyani_env
(pyani_env) angelikakiepas@Angelikas-MacBook-Pro ~ % conda list
# packages in environment at /opt/anaconda3/envs/pyani_env:
#
# Name                    Version                   Build  Channel
biopython                 1.83             py39ha09f3b3_0    conda-forge
blast                     2.15.0          pl5321h91c44f7_1    bioconda
blast-legacy              2.2.26               h527b516_3    bioconda
brotli                    1.1.0                h0dc2134_1    conda-forge
brotli-bin                1.1.0                h0dc2134_1    conda-forge
bzip2                     1.0.8                h10d778d_5    conda-forge
c-ares                    1.27.0               h10d778d_0    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0            py39h6be1789_0    conda-forge
curl                      8.6.0                h726d00d_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
entrez-direct             21.6                 h193322a_0    bioconda
fonttools                 4.49.0           py39ha09f3b3_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
importlib-resources       6.3.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.3.0              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5            py39h8ee36c8_1    conda-forge
krb5                      1.21.2               hb884880_0    conda-forge
lcms2                     2.16                 ha2f27b4_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           21_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h0dc2134_1    conda-forge
libbrotlidec              1.1.0                h0dc2134_1    conda-forge
libbrotlienc              1.1.0                h0dc2134_1    conda-forge
libcblas                  3.9.0           21_osx64_openblas    conda-forge
libcurl                   8.6.0                h726d00d_0    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.19                 ha4e1b8e_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 h10d778d_2    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
libiconv                  1.17                 hd75f5a5_2    conda-forge
libidn2                   2.3.7                h10d778d_0    conda-forge
libjpeg-turbo             3.0.0                h0dc2134_1    conda-forge
liblapack                 3.9.0           21_osx64_openblas    conda-forge
libnghttp2                1.58.0               h64cf6d3_1    conda-forge
libopenblas               0.3.26          openmp_hfef2a42_0    conda-forge
libpng                    1.6.43               h92b6c6a_0    conda-forge
libsqlite                 3.45.2               h92b6c6a_0    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libtiff                   4.6.0                h684deea_2    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libwebp-base              1.3.2                h0dc2134_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               18.1.1               hb6ac08f_0    conda-forge
matplotlib-base           3.8.3            py39h7070ae8_0    conda-forge
mummer                    3.23                h589c0e0_12    bioconda
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncbi-vdb                  3.0.0           pl5321h9722bc1_0    bioconda
ncurses                   6.4                  h93d8f39_2    conda-forge
numpy                     1.26.4           py39h28c39a1_0    conda-forge
openjpeg                  2.5.2                h7310d3a_0    conda-forge
openssl                   3.2.1                hd75f5a5_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.1            py39haf03413_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
perl                      5.32.1          7_h10d778d_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h775f41a_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h775f41a_0    conda-forge
perl-encode               3.19            pl5321hb7f2c08_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.201           pl5321h7133b54_2    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321hcd10b59_5    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321ha5712d3_1    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h775f41a_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h775f41a_0    conda-forge
perl-storable             3.15            pl5321h775f41a_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
pillow                    10.2.0           py39hdd30358_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pyani                     0.2.12             pyhdfd78af_0    bioconda
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
python                    3.9.18          h7a9c478_1_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
scipy                     1.12.0           py39h0ed1e0f_2    conda-forge
seaborn                   0.13.2               hd8ed1ab_0    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_0    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
statsmodels               0.14.1           py39h5b4affa_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
unicodedata2              15.1.0           py39hdc70f33_0    conda-forge
wget                      1.21.4               hca547e6_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h8a1eda9_5    conda-forge
zstd                      1.5.5                h829000d_0    conda-forge
```

**Comment by ireneortega** [comment]
Here you have:

```
# packages in environment at /home/iortsan/anaconda3/envs/pyani_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
biopython                 1.83             py39hd1e30aa_0    conda-forge
blast                     2.12.0               hf3cf87c_4    bioconda
blast-legacy              2.2.26               h9ee0642_3    bioconda
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.27.0               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0            py39h7633fee_0    conda-forge
curl                      7.88.1               hdc1c0ab_1    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
entrez-direct             21.6                 he881be0_0    bioconda
fonttools                 4.49.0           py39hd1e30aa_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
importlib-resources       6.3.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.3.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py39h7633fee_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcurl                   7.88.1               hdc1c0ab_1    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
matplotlib-base           3.8.3            py39he9076e7_0    conda-forge
mummer                    3.23            pl5321hdbdd923_16    bioconda
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.4           py39h474f0d3_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.1            py39hddac248_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-encode               3.19            pl5321h166bdaf_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
pillow                    10.2.0           py39had0adad_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyani                     0.2.12             pyhdfd78af_0    bioconda
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
python                    3.9.18          h0755675_1_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.12.0           py39h474f0d3_2    conda-forge
seaborn                   0.13.2               hd8ed1ab_0    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_0    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
statsmodels               0.14.1           py39h44dd56e_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
unicodedata2              15.1.0           py39hd1e30aa_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

Thanks for you help!

**Comment by kiepczi** [comment]
From the output you provided, it looks like `numpy` has been installed. 

It might be worth checking that `numpy` has been added to you `PATH`. If not, adding it to your  `PATH` should solve the issue. It might be also worth it to install `pyANI` from source.

**Comment by widdowquinn** [comment]
Hi @ireneortega - I have also attempted to replicate your issue, and everything works as expected, for me:

```bash
% conda create --name issue_423_test python=3.9 pyani -y
% conda activate issue_423_test
% average_nucleotide_identity.py -h                                                                                        [11:09:48]
usage: average_nucleotide_identity.py [-h] [--version] -o OUTDIRNAME -i INDIRNAME [-v] [-f] [-s FRAGSIZE] [-l LOGFILE] [--skip_nucmer] [--skip_blastn] [--noclobber]
                                      [--nocompress] [-g] [--gformat GFORMAT] [--gmethod {mpl,seaborn}] [--labels LABELS] [--classes CLASSES]
                                      [-m {ANIm,ANIb,ANIblastall,TETRA}] [--scheduler {multiprocessing,SGE}] [--workers WORKERS] [--SGEgroupsize SGEGROUPSIZE]
                                      [--SGEargs SGEARGS] [--maxmatch] [--nucmer_exe NUCMER_EXE] [--filter_exe FILTER_EXE] [--blastn_exe BLASTN_EXE]
                                      [--makeblastdb_exe MAKEBLASTDB_EXE] [--blastall_exe BLASTALL_EXE] [--formatdb_exe FORMATDB_EXE] [--write_excel] [--rerender]
                                      [--subsample SUBSAMPLE] [--seed SEED] [--jobprefix JOBPREFIX]
```

The error message you are receiving indicates that the problem lies within the `pandas` package. Can you please start a Python REPL and try to import Pandas (while in that `conda` environment):

```bash
% python                                                                                                                   [11:13:10]
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:36:46)
[Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>>
```

If this throws the same error, you should raise this issue at the Pandas repo: https://github.com/pandas-dev/pandas/issues

Best wishes,

L.
