### ISSUE TITLE
Tests fail with MatPlotLib 2.0

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#50]
#### Summary:
`nosetest`s fail with the new `matplotlib`

#### Description:
Running `nosetests` fails with

```
======================================================================
ERROR: Write .png graphics with mpl
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/lpritc/Documents/Development/pyani/tests/test_graphics.py", line 60, in test_png_mpl
    draw_format_method("png", "mpl")
  File "/Users/lpritc/Documents/Development/pyani/tests/test_graphics.py", line 55, in draw_format_method
    params=method_params)
  File "/Users/lpritc/Documents/Development/pyani/pyani/pyani_graphics.py", line 322, in heatmap_mpl
    orientation='row')
  File "/Users/lpritc/Documents/Development/pyani/pyani/pyani_graphics.py", line 196, in add_mpl_dendrogram
    height_ratios=[1, 0.15])
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 345, in __init__
    height_ratios=height_ratios)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 47, in __init__
    self.set_height_ratios(height_ratios)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 76, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid

======================================================================
ERROR: Write .svg graphics with mpl
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/lpritc/Documents/Development/pyani/tests/test_graphics.py", line 65, in test_svg_mpl
    draw_format_method("svg", "mpl")
  File "/Users/lpritc/Documents/Development/pyani/tests/test_graphics.py", line 55, in draw_format_method
    params=method_params)
  File "/Users/lpritc/Documents/Development/pyani/pyani/pyani_graphics.py", line 322, in heatmap_mpl
    orientation='row')
  File "/Users/lpritc/Documents/Development/pyani/pyani/pyani_graphics.py", line 196, in add_mpl_dendrogram
    height_ratios=[1, 0.15])
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 345, in __init__
    height_ratios=height_ratios)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 47, in __init__
    self.set_height_ratios(height_ratios)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 76, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid

======================================================================
ERROR: Write .pdf graphics with mpl
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/lpritc/Documents/Development/pyani/tests/test_graphics.py", line 70, in test_pdf_mpl
    draw_format_method("pdf", "mpl")
  File "/Users/lpritc/Documents/Development/pyani/tests/test_graphics.py", line 55, in draw_format_method
    params=method_params)
  File "/Users/lpritc/Documents/Development/pyani/pyani/pyani_graphics.py", line 322, in heatmap_mpl
    orientation='row')
  File "/Users/lpritc/Documents/Development/pyani/pyani/pyani_graphics.py", line 196, in add_mpl_dendrogram
    height_ratios=[1, 0.15])
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 345, in __init__
    height_ratios=height_ratios)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 47, in __init__
    self.set_height_ratios(height_ratios)
  File "/Users/lpritc/Documents/Development/pyani/venv-pyani-devel/lib/python3.6/site-packages/matplotlib/gridspec.py", line 76, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid
```

#### Reproducible Steps:
* clone `pyani`
* create virtualenv and install requirements
* run `nosetests`

#### pyani Version:
0.2.1

#### Python Version:
3.6

#### Operating System:
OSX

**Comment by widdowquinn** [comment]
Fix implemented in https://github.com/widdowquinn/pyani/commit/e46c7f5f27e4b44219bdab6a674b63bbf65f0767
