### ISSUE TITLE
local variable 'filestem' referenced before assignment in all methods except TETRA

### ISSUE THREAD

**Issue by ntopaz** [widdowquinn/pyani#52]
Thank you for this script. I keep running into this issue when running ANIm or ANIb. It does not seem to be present when using TETRA

#### Summary:
Please provide a short summary (a couple of sentences).

Using the command: average_nucleotide_identity.py -v -i tests/reference/ -o tests/output/ -m ANIm -g --gformat pdf --labels tests/labels -l log_test -f

#### Description:
Describe the issue as clearly as possible.

It generates the NUCmer command-lines, then produces the following:

INFO: Command pool done.
INFO: Cumulative return value: 0
INFO: All multiprocessing jobs complete.
INFO: Processing NUCmer .delta files.
INFO: Compressing/deleting tests/output/nucmer_output
INFO: 	Compressing output from tests/output/nucmer_output to tests/output/nucmer_output.tar.gz
INFO: 	Removing output directory tests/output/nucmer_output
INFO: Writing ANIm results to tests/output/
Traceback (most recent call last):
  File "/bin/average_nucleotide_identity.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyani==0.2.1.dev0', 'average_nucleotide_identity.py')
  File "/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1505, in run_script
    exec(script_code, namespace, namespace)
  File "/lib/python3.6/site-packages/pyani-0.2.1.dev0-py3.6.egg/EGG-INFO/scripts/average_nucleotide_identity.py", line 781, in <module>
  File "/lib/python3.6/site-packages/pyani-0.2.1.dev0-py3.6.egg/EGG-INFO/scripts/average_nucleotide_identity.py", line 596, in write
UnboundLocalError: local variable 'filestem' referenced before assignment

#### pyani Version:
0.2.1.dev
#### Python Version:
3.6.0
#### Operating System:
CentOS 6.8

**Comment by widdowquinn** [comment]
Hi - you've closed the issue - what happened?

**Comment by ntopaz** [comment]
My apologies, I forgot I was using the dev version rather than release

**Comment by widdowquinn** [comment]
No worries - that's still a bug I need to squash though, so I'll reopen it.

**Comment by widdowquinn** [comment]
That should be fixed with https://github.com/widdowquinn/pyani/commit/f97e35b770f21d243a1564e67cfb2bb46310b44c - please do reopen this, if it recurs.

L.
