### ISSUE TITLE
"CXXABI_1.3.9' not found" error

### ISSUE THREAD

**Issue by mikaells** [widdowquinn/pyani#96]
#### Summary:
Hi, I installed pyani through conda and I am getting a "CXXABI_1.3.9' not found" error. No errors in installation

#### Reproducible Steps:
conda install pyani
average_nucleotide_identity.py 

#### Current Output:
Traceback (most recent call last):
  File "/home/odin/.conda/envs/py36/bin/average_nucleotide_identity.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyani==0.2.3', 'average_nucleotide_identity.py')
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/pyani-0.2.3-py3.6.egg/EGG-INFO/scripts/average_nucleotide_identity.py", line 169, in <module>
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/pyani-0.2.3-py3.6.egg/pyani/pyani_graphics.py", line 29, in <module>
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/cluster/__init__.py", line 27, in <module>
    from . import vq, hierarchy
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 179, in <module>
    import scipy.spatial.distance as distance
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/spatial/__init__.py", line 93, in <module>
    from .kdtree import *
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /home/odin/.conda/envs/py36/lib/python3.6/site-packages/matplotlib/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)

#### pyani Version:
0.2.3
#### Python Version:
3.6
#### Operating System:
Ubuntu 17.04

**Comment by widdowquinn** [comment]
Hi Mikaells,

I'm afraid that I don't maintain the conda installation (I don't use conda at all, in fact), so I may be of limited use to you with this.

From the error message you get, it appears that the problem originates in one of `pyani`'s dependencies - `scipy`:

```
File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/cluster/init.py", line 27, in 
from . import vq, hierarchy
File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 179, in 
import scipy.spatial.distance as distance
File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/spatial/init.py", line 93, in 
from .kdtree import *
File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/spatial/kdtree.py", line 8, in 
import scipy.sparse
File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/sparse/init.py", line 229, in 
from .csr import *
File "/home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/sparse/csr.py", line 15, in 
from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, 
ImportError: /home/odin/.conda/envs/py36/lib/python3.6/site-packages/matplotlib/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/odin/.conda/envs/py36/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)
```

Specifically, it doesn't seem to be able to find the C++ ABI library. My first guess is that the version of `scipy` installed by `conda` was compiled against a version of C++ that is different to the libraries being pointed to, on your system.

StackOverflow (as ever) suggests several routes to fixing this, but the specific fix may depend on your system:

* [C++ ABI 1.3.8 not found](https://stackoverflow.com/questions/23494103/version-cxxabi-1-3-8-not-found-required-by)
* [CXXABI_1.3.8 not found](https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx)

other people have noticed the same issue with `anaconda`:

* [CXXABI_1.3.9 not included in libstdc++.so.6](https://github.com/ContinuumIO/anaconda-issues/issues/5191)

and in your case - like the issue linked above - this may be because your OS (CentOS 17.04) is ahead of the `anaconda` releases/package builds. If you are able to be patient, I expect they will catch up.

This appears to be an issue that has arisen before with `anaconda`:

* [TF Quit working with /lib/libstdc++.so.6](https://github.com/tensorflow/tensorflow/issues/5017)

and I'm afraid that the problem is one that I am unable to fix, as it doesn't originate from `pyani`, but is likely an incompatibility between `anaconda` and your OS within the `anaconda` environment, that will affect all applications using that bit of `scipy` code.

Many apologies,

L.

**Comment by mikaells** [comment]
Hi Leighton,

 

Appreciate the fast response

 

I ran it with python 3.5 (e.g. made a new conda environment with python 3.5) and I ran without issue.

 

Thanks!

 

-Mikael

**Comment by jmartin18** [comment]
I was able to solve by pip uninstalling/reinstalling scipy

**Comment by monajalal** [comment]
In my case I installed the keras and installed it using following command and the error resolved. I got the same exact error as you and doing what @jmartin18 said didn't solve my problem 
`sudo conda install -c anaconda keras-gpu `

**Comment by widdowquinn** [comment]
@monajalal - is your problem with a `pyani` installation, or with `keras-gpu`? If it is with `keras`, you should raise this issue with that project, rather than here.
